### ISSUE TITLE
Symbol not found: _rb_cObject on M1 Mac

### ISSUE THREAD

**Issue by gisborne** [ruby-debug/debase#105]
Ruby 3.2.1, MacOS 13.4.1 ©

Trying to use debugger from IntelliJ gives me this:

```
/bin/zsh -c "bash -c 'env RBENV_VERSION=3.2.1 /opt/homebrew/Cellar/rbenv/1.2.0/libexec/rbenv exec ruby -x /Users/gisborne/Documents/01-projects/samples/fleetio-web-assessment-gisborne/bin/bundle exec ruby /Users/gisborne/.gem/gems/ruby-debug-ide-3.0.0.beta.10/bin/rdebug-ide --key-value --step-over-in-blocks --disable-int-handler --evaluation-timeout 10 --evaluation-control --time-limit 100 --memory-limit 0 --full-value-time-limit 20000 --full-value-memory-limit 0 --rubymine-protocol-extensions --port 58896 --host 0.0.0.0 --dispatcher-port 58897 -- /Users/gisborne/Documents/01-projects/samples/fleetio-web-assessment-gisborne/bin/rails server -b 0.0.0.0 -p 3000 -e development'"
<internal:/Users/gisborne/.rbenv/versions/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': dlopen(/Users/gisborne/.gem/gems/debase-3.0.0.beta.6/lib/debase_internals.bundle, 0x0009): Symbol not found: _rb_cObject (LoadError)
  Referenced from: <83018DDB-FB94-345D-9BC7-B1BDC874AE05> /Users/gisborne/.gem/gems/debase-3.0.0.beta.6/lib/debase_internals.bundle
  Expected in:     <5DBD9698-A0CA-3E81-88A3-17E71990A2E9> /Users/gisborne/.rbenv/versions/3.2.1/bin/ruby - /Users/gisborne/.gem/gems/debase-3.0.0.beta.6/lib/debase_internals.bundle
	from <internal:/Users/gisborne/.rbenv/versions/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/gisborne/.gem/gems/debase-3.0.0.beta.6/lib/debase.rb:4:in `<top (required)>'
	from <internal:/Users/gisborne/.rbenv/versions/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/gisborne/.rbenv/versions/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/gisborne/.gem/gems/ruby-debug-ide-3.0.0.beta.10/lib/ruby-debug-ide.rb:5:in `<top (required)>'
	from <internal:/Users/gisborne/.rbenv/versions/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/gisborne/.rbenv/versions/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/gisborne/.gem/gems/ruby-debug-ide-3.0.0.beta.10/bin/rdebug-ide:26:in `<main>'

Process finished with exit code 1
```

The gem builds fine.

I've tried  setting 0.2.5 beta 2 in my Gemfile with the same result.

**Comment by sixtyfive** [comment]
On the topic of `0.2.5.beta2` ... are there plans for releasing `0.2.6` any time soon? The last non-beta release was in 2019, four years ago. Just alone the fact that there is now a new architecture, widely used amongst developers, probably Ruby developers especially, would make it real helpful if `0.2.5.beta2` could simply be released as `0.2.6`...
