### ISSUE TITLE
Conditional breakpoints keep debugger from starting

### ISSUE THREAD

**Issue by Ipecac242** [ruby-debug/debase#11]
When I have any conditional breakpoints set, the ruby debugger fails to start.  I made a breakpoint conditional in Netbeans by left-clicking to the left of the code line, then right-clicking the red square breakpoint symbol, choosing Breakpoint / Properties, then in the condition field, I put an expression, like i == 4.  Next, I start debugging and the debugger doesn't start.  If I remove the conditional from the breakpoint, it works OK.

I see in the IDE log the error:  13020: Exception in DebugThread loop: undefined method `expr=' for #Debase::Breakpoint:0x5a4ab8

I'm using Windows 7 64-bit, Netbeans 7.4, Ruby200-p451 32-bits, ruby-debug-ide-0.4.22, debase 0.0.9.

Here are the IDE log details:

```
Fast Debugger (ruby-debug-ide 0.4.22, debase 0.0.9) listens on 127.0.0.1:64944
13020: Exception in DebugThread loop: undefined method `expr=' for #<Debase::Breakpoint:0x5a4ab8>
Backtrace:
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:26:in `block in execute'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:24:in `each'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:24:in `execute'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:90:in `block in process_commands'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:87:in `catch'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:87:in `process_commands'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide.rb:122:in `block in start_control'
INFO [org.netbeans.api.extexecution.ExecutionService]
org.rubyforge.debugcommons.RubyDebuggerException: Trying to send a command [start] to non-started or finished proxy (debuggee: RubyDebugTarget@840462048[baseDir: C:\Repositories\3D-tests-git\gfxsv3d-src\3D\Basic\Render, debuggedFile: C:\Repositories\3D-tests-git\gfxsv3d-src\3D\Basic\Render\Test.rb, port: 64944], output: 
Error Output: 
C:/testdev/Ruby200-p451/lib/ruby/2.0.0/rubygems/specification.rb:643: warning: warning: Invalid argument:C:/Users/mswither.AMR/.gem/ruby/2.0.0:C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/specifications: Invalid argument
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/bin/rdebug-ide:24: warning: shadowing outer local variable - opts
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/xml_printer.rb:281: warning: assigned but unused variable - e
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/xml_printer.rb:297: warning: mismatched indentations at 'end' with 'if' at 293
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:34: warning: shadowing outer local variable - input
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:135: warning: assigned but unused variable - context
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:15: warning: shadowing outer local variable - largest
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/enable.rb:6: warning: shadowing outer local variable - largest
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/jump.rb:70: warning: mismatched indentations at 'end' with 'def' at 62
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/pause.rb:30: warning: mismatched indentations at 'end' with 'def' at 26
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/set_type.rb:44: warning: mismatched indentations at 'end' with 'def' at 38
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide.rb:102: warning: instance variable @control_thread not initialized
Fast Debugger (ruby-debug-ide 0.4.22, debase 0.0.9) listens on 127.0.0.1:64944
13020: Exception in DebugThread loop: undefined method `expr=' for #<Debase::Breakpoint:0x5a4ab8>
Backtrace:
C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:26:in `block in execute'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:24:in `each'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:24:in `execute'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:90:in `block in process_commands'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:87:in `catch'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:87:in `process_commands'
  from: C:/testdev/Ruby200-p451/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide.rb:122:in `block in start_control'
    at org.rubyforge.debugcommons.RubyDebuggerProxy.sendCommand(RubyDebuggerProxy.java:335)
    at org.rubyforge.debugcommons.RubyDebuggerProxy.attachToRubyDebug(RubyDebuggerProxy.java:164)
    at org.rubyforge.debugcommons.RubyDebuggerProxy.attach(RubyDebuggerProxy.java:124)
    at org.netbeans.modules.ruby.debugger.RubyDebugger.debug(RubyDebugger.java:143)
Caused: java.lang.RuntimeException
    at org.netbeans.modules.ruby.debugger.RubyDebugger.debug(RubyDebugger.java:153)
    at org.netbeans.modules.ruby.platform.execution.RubyProcessCreator.call(RubyProcessCreator.java:114)
    at org.netbeans.modules.ruby.platform.execution.RubyProcessCreator.call(RubyProcessCreator.java:60)
[catch] at org.netbeans.api.extexecution.ExecutionService$3.call(ExecutionService.java:258)
    at org.netbeans.api.extexecution.ExecutionService$3.call(ExecutionService.java:234)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1432)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2042)
```

**Comment by os97673** [comment]
Could you please try breakpoint-expr-writer branch and let me know if it fixes the problem or not.

**Comment by dawez** [comment]
It seems that I have the same problem. I tried with different combinations of byebug / debase.

gem 'byebug' , github: 'deivid-rodriguez/byebug', branch: 'master'
gem 'debase' , :github => 'denofevil/debase', :branch => 'master'

With this combination the page is does not finish loading  and it is stop in loading mode.
Using instead 

byebug (3.5.1 7c8c0db)
debase (0.1.2)

The page is loaded but there no stopping at breakpoint. There is a error message appearing on top: "No interface loaded"

I am using ruby 2.2.0p0 (2014-12-25 revision 49005) [i686-linux]

Anything else that I can try ?

**Comment by os97673** [comment]
debase is not supposed to work with byebug,  why do you use it?  And what are you trying to achieve?

**Comment by Ipecac242** [comment]
Hi os97673,

Sorry for the delay in checking your breakpoint-expr-writer branch fix for this.  I tried it today and get a different error now:

```
SEVERE [org.rubyforge.debugcommons.Util]: Error Output: 
C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/specification.rb:627: warning: warning: Invalid argument:C:/Users/mswither/.gem/ruby/2.0.0:C:/Dev/Ruby200/lib/ruby/gems/2.0.0/specifications: Invalid argument
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/bin/rdebug-ide:24: warning: shadowing outer local variable - opts
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/xml_printer.rb:281: warning: assigned but unused variable - e
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/xml_printer.rb:297: warning: mismatched indentations at 'end' with 'if' at 293
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:34: warning: shadowing outer local variable - input
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:135: warning: assigned but unused variable - context
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:15: warning: shadowing outer local variable - largest
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/enable.rb:6: warning: shadowing outer local variable - largest
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/jump.rb:70: warning: mismatched indentations at 'end' with 'def' at 62
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/pause.rb:30: warning: mismatched indentations at 'end' with 'def' at 26
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/set_type.rb:44: warning: mismatched indentations at 'end' with 'def' at 38
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide.rb:102: warning: instance variable @control_thread not initialized
Fast Debugger (ruby-debug-ide 0.4.22, debase 0.1.3.pre1) listens on 127.0.0.1:57718
1216: Exception in DebugThread loop: wrong number of arguments (1 for 0)
Backtrace:
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:26:in `expr='
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:26:in `block in execute'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:24:in `each'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:24:in `execute'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:90:in `block in process_commands'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:87:in `catch'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:87:in `process_commands'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide.rb:122:in `block in start_control'
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Indexing of: C:\Repo\UserClass took: 285 ms (New or modified files: 0, Deleted files: 0) [Adding listeners took: 3 ms]
INFO [org.netbeans.api.extexecution.ExecutionService]
org.rubyforge.debugcommons.RubyDebuggerException: Trying to send a command [start] to non-started or finished proxy (debuggee: RubyDebugTarget@66110490[baseDir: C:\Repo\3D-Git\3D\Basic\Render, debuggedFile: C:\Repo\3D-Git\3D\Basic\Render\MsaaBasic.gsf, port: 57718], output: 
Error Output: 
C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/specification.rb:627: warning: warning: Invalid argument:C:/Users/mswither/.gem/ruby/2.0.0:C:/Dev/Ruby200/lib/ruby/gems/2.0.0/specifications: Invalid argument
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/bin/rdebug-ide:24: warning: shadowing outer local variable - opts
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/xml_printer.rb:281: warning: assigned but unused variable - e
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/xml_printer.rb:297: warning: mismatched indentations at 'end' with 'if' at 293
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:34: warning: shadowing outer local variable - input
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:135: warning: assigned but unused variable - context
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:15: warning: shadowing outer local variable - largest
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/enable.rb:6: warning: shadowing outer local variable - largest
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/jump.rb:70: warning: mismatched indentations at 'end' with 'def' at 62
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/pause.rb:30: warning: mismatched indentations at 'end' with 'def' at 26
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/set_type.rb:44: warning: mismatched indentations at 'end' with 'def' at 38
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide.rb:102: warning: instance variable @control_thread not initialized
Fast Debugger (ruby-debug-ide 0.4.22, debase 0.1.3.pre1) listens on 127.0.0.1:57718
1216: Exception in DebugThread loop: wrong number of arguments (1 for 0)
Backtrace:
C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:26:in `expr='
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:26:in `block in execute'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:24:in `each'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/commands/condition.rb:24:in `execute'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:90:in `block in process_commands'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:87:in `catch'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:87:in `process_commands'
  from: C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide.rb:122:in `block in start_control'
	at org.rubyforge.debugcommons.RubyDebuggerProxy.sendCommand(RubyDebuggerProxy.java:335)
	at org.rubyforge.debugcommons.RubyDebuggerProxy.attachToRubyDebug(RubyDebuggerProxy.java:164)
	at org.rubyforge.debugcommons.RubyDebuggerProxy.attach(RubyDebuggerProxy.java:124)
	at org.netbeans.modules.ruby.debugger.RubyDebugger.debug(RubyDebugger.java:143)
Caused: java.lang.RuntimeException
	at org.netbeans.modules.ruby.debugger.RubyDebugger.debug(RubyDebugger.java:153)
	at org.netbeans.modules.ruby.platform.execution.RubyProcessCreator.call(RubyProcessCreator.java:114)
	at org.netbeans.modules.ruby.platform.execution.RubyProcessCreator.call(RubyProcessCreator.java:60)
[catch] at org.netbeans.api.extexecution.ExecutionService$3.call(ExecutionService.java:258)
	at org.netbeans.api.extexecution.ExecutionService$3.call(ExecutionService.java:234)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by Ipecac242** [comment]
I tried a simple fix for the the error I'm getting now by changing 

```
rb_define_method(cBreakpoint, "expr=", Breakpoint_set_expr, 0);
```

to

```
rb_define_method(cBreakpoint, "expr=", Breakpoint_set_expr, 1);
```

It got past the arguments error, but it seems to ignore the condition and breaks even when the condition is false.

**Comment by os97673** [comment]
@Ipecac242 it looks like you need to learn me how to use the IDE of your choice so I could fix all such problems without asking you to test every my change.
What IDE are you using, is there any documentation on how to use it do debug ruby script?

**Comment by Ipecac242** [comment]
Thanks for your help on this.  I'm currently using Netbeans 8.0.1.  You can get the ruby plugins for Netbeans here:  http://plugins.netbeans.org/plugin/38549

There is also some info on using Ruby in Netbeans here:  http://wiki.netbeans.org/Ruby

**Comment by hurricup** [comment]
Closing this as abandoned, feel free to provide more recent information if any.
